#
#  .travis.yml
#  OAuth
#  
#  Created by Sinoru on 2016. 12. 2..
#  Copyright © 2016 Sinoru. All rights reserved.

language: swift
matrix:
  include:
    - os: linux
      language: generic
      dist: trusty
      sudo: required
    - os: osx
      osx_image: xcode8.1
install:
  - eval "$(curl -sL https://gist.githubusercontent.com/kylef/5c0475ff02b7c7671d2a/raw/9f442512a46d7a2af7b850d65a7e9bd31edfb09b/swiftenv-install.sh)"
  - brew install swiftlint
script:
  - swiftlint
  - swift test
